server:
  port: 8081

spring:
  application:
    name: denuncieja
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=DenuncieJa
    username: sa
    password: my!SqlServer2020
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
