server:
  port: 8081

spring:
  application:
    name: highlighter
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

#  datasource:
#    url: jdbc:mysql://localhost:3306/DenuncieJa
#    username: root
#    password: 123456789
#    driverClassName: com.mysql.jdbc.Driver
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=DenuncieJa
    username: sa
    password: my!SqlServer2020
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
